apiVersion : apps/v1
kind: Deployment
metadata:
  name: firstappdemo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstappdemo
  template:
    metadata:
      labels:
        app: firstappdemo 
    spec:
      containers:
        - name: firstappdemo 
          image: k8simagerepository.azurecr.io/firstappdemo
          ports:
          - containerPort: 5006